-- Centres d'intérêt supplémentaires (exécuter après 00003)
INSERT INTO interests (name, slug)
SELECT v.name, v.slug
FROM (VALUES
  ('Sciences', 'sciences'),
  ('Histoire', 'histoire'),
  ('Droit & justice', 'droit-justice'),
  ('International', 'international'),
  ('Médias & presse', 'medias-presse'),
  ('Religion & spiritualité', 'religion-spiritualite'),
  ('Psychologie', 'psychologie'),
  ('Entrepreneuriat', 'entrepreneuriat'),
  ('Gaming & esport', 'gaming-esport'),
  ('Crypto & Web3', 'crypto-web3'),
  ('Art & design', 'art-design'),
  ('Musique', 'musique'),
  ('Cinéma & séries', 'cinema-series'),
  ('Actualité', 'actualite'),
  ('Immigration', 'immigration'),
  ('Droits humains', 'droits-humains'),
  ('Innovation', 'innovation'),
  ('Startups', 'startups'),
  ('Énergie', 'energie'),
  ('Agriculture & alimentation', 'agriculture-alimentation'),
  ('Géopolitique', 'geopolitique'),
  ('Défense & sécurité', 'defense-securite'),
  ('Espace & astronomie', 'espace-astronomie'),
  ('Biologie & santé publique', 'biologie-sante-publique'),
  ('Climat & écologie', 'climat-ecologie'),
  ('Intelligence artificielle', 'intelligence-artificielle'),
  ('Éthique & morale', 'ethique-morale'),
  ('Famille & parentalité', 'famille-parentalite'),
  ('Égalité & genre', 'egalite-genre'),
  ('Urbanisme & villes', 'urbanisme-villes'),
  ('Transport & mobilité', 'transport-mobilite'),
  ('Travail & emploi', 'travail-emploi'),
  ('Logement', 'logement'),
  ('Finance personnelle', 'finance-personnelle'),
  ('Littérature', 'litterature'),
  ('Mode & lifestyle', 'mode-lifestyle'),
  ('Animaux & nature', 'animaux-nature'),
  ('Éducation numérique', 'education-numerique'),
  ('Santé mentale', 'sante-mentale'),
  ('Sport extrême', 'sport-extreme')
) AS v(name, slug)
WHERE NOT EXISTS (SELECT 1 FROM interests i WHERE i.slug = v.slug);
